dependencies:
 - python=3.7
 - numpy
 - scipy
 - pytorch
 - cudatoolkit=10.0
 - matplotlib
 - tensorflow
 - pip:
    - gym
    - tensorboardX
    - crc32c
    - sphinx
    - recommonmark
    - sphinx_rtd_theme
